display log in container
ABAP-Logger/ABAP-Logger pull request #135
Opened 2023-04-13 21:32 UTC by Ennowulff

so far it is not possible to display a log in a container.
added method CONTAINER to interface ZIF_LOGGER and implementation to ZCL_LOGGER.

```
REPORT zlogger_demo_07.

PARAMETERS p_info  TYPE c LENGTH 70 DEFAULT TEXT-001 MODIF ID dsp. "PRESS ENTER TO DISPLAY LOG
PARAMETERS p_info2 TYPE c LENGTH 70 DEFAULT TEXT-002 MODIF ID dsp. "PRESS ENTER AGAIN TO REFRESH LOG

INITIALIZATION.
  "create docking container
  DATA docker TYPE REF TO cl_gui_docking_container.
  CREATE OBJECT docker
    EXPORTING
      no_autodef_progid_dynnr = abap_true
      ratio                   = 80
      side                    = cl_gui_docking_container=>dock_at_bottom.
  "create display profile
  DATA my_profile TYPE REF TO zif_logger_display_profile.
  my_profile = zcl_logger_factory=>create_display_profile(
                 i_single_log  = abap_true )->set_grid( abap_true ).

  "Create logger
  DATA my_logger TYPE REF TO zif_logger.
  my_logger = zcl_logger_factory=>create_log( desc = 'ABAP Logger Demo 07' ) ##no_text.

AT SELECTION-SCREEN OUTPUT.
  "hide parameters (for information only)
  LOOP AT SCREEN.
    IF screen-group1 = 'DSP'.
      screen-input = '0'.
      MODIFY SCREEN.
    ENDIF.
  ENDLOOP.

AT SELECTION-SCREEN.

  "put some messages
  my_logger->w( obj_to_log = 'demonstration warning' ).
  my_logger->e( obj_to_log = 'demonstration error' ).
  my_logger->s( obj_to_log = 'demonstration success' ).

  "Display messages in container
  my_logger->container(
    i_container       = docker
    i_display_profile = my_profile->get( ) ).

START-OF-SELECTION.
```

2023-04-14 03:47 UTC, larshp commented
@Ennowulff small trick, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks for how to get syntax highlighting in the code block comments

2023-04-29 13:12 UTC, christianguenter2 requested changes
Two small remarks, otherwise we are good to go 👍

2023-04-29 13:12 UTC, christianguenter2 commented on src/zcl_logger.clas.abap
> +          OTHERS              = 1.
If these never fails what about adding
```ABAP
ASSERT sy-subrc = 0.
```
?

2023-04-29 13:12 UTC, christianguenter2 commented on src/zcl_logger.clas.abap
> +          i_t_log_handle   = log_handles.
There are the exceptions 
```ABAP
  EXCEPTIONS
    CONTROL_NOT_FOUND
    INTERNAL_ERROR.
```
in my system. What about catching them?

2023-04-29 13:15 UTC, christianguenter2 commented
Can you add your demo report here?
https://github.com/ABAP-Logger/demos

2023-04-29 14:17 UTC, Ennowulff commented
> Can you add your demo report here? https://github.com/ABAP-Logger/demos

I will after the ür is done. otherwise there will be an error in the demo-repo because of the missing method.

2023-04-29 15:08 UTC, christianguenter2 commented
> > Can you add your demo report here? https://github.com/ABAP-Logger/demos
> 
> I will after the ür is done. otherwise there will be an error in the demo-repo because of the missing method.

You could create a pr in the demo repo and link both together? Of course it should be merged only after this is merged.

2023-04-30 09:23 UTC, christianguenter2 approved these changes
:+1

2023-09-28 09:12 UTC, AlexandreHT commented
Thanks for the PR.
Quick RFC before merging: this would be the third method for displaying the log. Wouldn't it be better if they were prefixed by display_ (display_fullscreen, display_popup, display_in_container)?
That would required aliases for backward compatibility for some time but we could start fresh for this method.

2023-11-19 23:59 UTC, mbtools commented
We should merge #145 before resolving the conflict here. Otherwise LGTM.

2023-12-05 21:15 UTC, mbtools approved these changes
Works well. Demo in https://github.com/ABAP-Logger/demos/pull/6

Thanks, @Ennowulff !

PS: Gut Ding will Weile haben 😉

2023-12-08 11:22 UTC, merged

2023-12-08 11:22 UTC, AlexandreHT commented
Thanks