Loggable Object Interface
ABAP-Logger/ABAP-Logger pull request #90
Opened 2021-09-16 12:28 UTC by cavabap

Hello Project Team

Sorry it took longer than a few weeks
Here is my suggested solution for creating an interface ZIF_LOGGABLE_OJBECT for a loggable object. See Issue #85 and #67 

I also think it would be good to create a private method for logging tables of BAPIRET2: Pleas see my comment and ADT LInk.

With kind regards

Martin Cavanagh

2021-09-20 12:34 UTC, AlexandreHT requested changes

2021-09-20 12:34 UTC, AlexandreHT commented on src/zif_loggable_object.intf.abap
> +    METHODS get_message_table RETURNING VALUE(r_result) TYPE bapiret2_t.
I'm not sure bapiret2 is polyvalent enough for the interface. In #67, I was thinking of an zif_loggable_object as a proxy of zif_logger. bapiret2 won't allow us to store string and exceptions.

2021-09-20 15:54 UTC, cavabap commented on src/zif_loggable_object.intf.abap
> +    METHODS get_message_table RETURNING VALUE(r_result) TYPE bapiret2_t.
I think I've implemented part of your suggestion,
>>create a new interface zif_loggable_object with one method get_message_table. For me, message_tables are bpairet2_t .

I also think this would work just fine,

`data(notification) = model->validate( ).
if notification->has_error( ) = abap_true.
  logger->add_loggable_object( notification ).
endif.
`

Actually my main use case is for exceptions which are bapiret2_t capable - so I guess I didn't really see the problem of working with a string. Also exceptions which don't implement zif_loggable_object can still be logged as is. 

So do you want to zif_logger to call zif_loggable_object which then calls zif_logger? I usually like to avoid those kind of cyclic dependencies.

Can you submit an improvement to my pull request? or can you be more explicit? How do you imagine the returning parameter of method get_message_table? type standard table of any?

2021-09-20 17:19 UTC, pokrakam commented on src/zif_loggable_object.intf.abap
> +    METHODS get_message_table RETURNING VALUE(r_result) TYPE bapiret2_t.
Interesting ideas. If I may chime in, I don't feel that a generic parameter is ideal. It puts the onus on the caller, who may not know what is being logged from where.
I would suggest `get_messages_as_bapiret2` `get_messages_as text` `get_exceptions` etc. It means that each one needs to do mapping for other types but at least all bases are covered. 
Or a bunch of `exporting` parameters filled with `if ... is requested`, but personally I prefer separate methods.

2021-09-20 20:05 UTC, AlexandreHT commented on src/zif_loggable_object.intf.abap
> +    METHODS get_message_table RETURNING VALUE(r_result) TYPE bapiret2_t.
@cavabap: I would like to start by apologizing for the shortness of my review (I'm going to elaborate now).
@pokrakam with pleasure: the more the merrier

In the #67 context, the idea was to create an interface with the sole purpose of being loggable by zif_logger. Therefore the only caller should be an instance of zif_logger.  adding different retrieval methods would not really help in the regard + in order to store all the messages logged in the objet, we'll need a unique table to keep the log sequence.

I made a PR to your repo (https://github.com/cavabap/ABAP-Logger/pull/3) that implements what I was thinking about.

As a user of ABAP-Logger Library (therefore outside the scope of ABAP Logger repo), I would create the following object:
```ABAP
class zcl_notification definition.
  public section.
    interfaces zif_loggable_object.

  methods add, s, i, e, w, a "with a signature similar to zif_logger.
    
  methods has_message, has warning, has_error...

  private section.
    data: messages type zif_loggable_object=>tty_message.
endclass.

class zcl_notification definition.

  method zif_logger~a, e, i, s, w
    "same as zcl_logger
  endmethod.


  method zif_logger~add.
    data detailed_msg type zif_loggable_object=>ty_message.

    msg_type = cl_abap_typedescr=>describe_by_data( obj_to_log ).

    if obj_to_log is not supplied.
      detailed_msg-symsg-sgty = sy-msgty.
      detailed_msg-symsg-msgid = sy-msgid.
      detailed_msg-symsg-msgno = sy-msgno.
      detailed_msg-symsg-msgv1 = sy-msgv1.
      detailed_msg-symsg-msgv2 = sy-msgv2.
      detailed_msg-symsg-msgv3 = sy-msgv3.
      detailed_msg-symsg-msgv4 = sy-msgv4.

    elseif msg_type->type_kind = cl_abap_typedescr=>typekind_oref.
     detailed_msg-exception = obj_to_log.

   endif.
   append detailed_msg to messages.

    self = me.
  endmethod.
endclass.
```

2021-09-20 20:47 UTC, cavabap commented on src/zif_loggable_object.intf.abap
> +    METHODS get_message_table RETURNING VALUE(r_result) TYPE bapiret2_t.
So I see in the PR to my repo how that would work. And I guess I'm fine with it (except wouldn't you have just broken my unit tests? I didn't see any unit adjusted unit tests).

But I'm totally lost on your example as to why you would want to re-implemnt the zif_logger as a user...
Anyway I guess it doesn't really matter to me. I can handle a more complicated signature as you've provided.

2021-09-20 21:04 UTC, cavabap commented on src/zif_loggable_object.intf.abap
> +    METHODS get_message_table RETURNING VALUE(r_result) TYPE bapiret2_t.
So I corrected the error in the POC you submitted.
However `context type simple` , is not valid in a structure and I'm not sure what you want to achieve.
Can you have review you thoughts? And at any rate I thought the context is always supplied by the add method?

2021-09-21 05:25 UTC, AlexandreHT commented on src/zif_loggable_object.intf.abap
> +    METHODS get_message_table RETURNING VALUE(r_result) TYPE bapiret2_t.
`(except wouldn't you have just broken my unit tests? I didn't see any unit adjusted unit tests).`
It was more POC than productive code, I agree. I'll make another PR. 

`But I'm totally lost on your example as to why you would want to re-implemnt the zif_logger as a user...`
In my system there are more than one logging tools in use. Using a notification zif_logger-like class in a model class allow me to let the consumer class choose which logger to use. I could have created an adapter class for the other logger that implements zif_logger but not all the methods are relevant (fullscreen, popup...)

For the context part, you're right, it may be not relevant in the zif_loggable_object case

2021-09-21 06:08 UTC, larshp commented on src/zif_loggable_object.intf.abap
> +           tty_message type standard table of ty_message with empty key.
EMPTY KEY only works from v740sp02, https://syntax.abaplint.org/?filter=types#/expression/TypeTableKey
```suggestion
           tty_message type standard table of ty_message with default key.
```

2021-09-21 06:35 UTC, cavabap commented on src/zif_loggable_object.intf.abap
> +    METHODS get_message_table RETURNING VALUE(r_result) TYPE bapiret2_t.
Ok, I've removed the context part.
You should add some unit tests for your other types other than the sy_msg (strings, exceptions, etc).

In general I feel that zif_loggable_object is very complex. Perhaps you need this complexity - but many users might not. I would like to suggest we provide two interfaces: 1. zif_loggable_object with the signature I originally provided and 2. zif_loggable_object_complex with its current more flexible but more complex signature.

Otherwise the method zif_logger~add is a little bit long in my opinion. I think it would be good idea to look at increasing the modularisation. The method begins with 30 odd lines of declarations, which I imagine are mostly used in only one or two IF blocks. And my PR for example adt://S4H/sap/bc/adt/oo/classes/zcl_logger/source/main#start=388,0;end=406,18 could belong nicely in its own private method add_loggable_object(). The same could be done for a lot of the other if blocks. But I guess you have a reason why your not doing that?

Thanks for all your work on this great logging framework

2021-09-21 17:22 UTC, AlexandreHT commented on src/zif_loggable_object.intf.abap
> +    METHODS get_message_table RETURNING VALUE(r_result) TYPE bapiret2_t.
`Otherwise the method zif_logger~add is a little bit long in my opinion.`
Agreed. I had started to create a helper class as exposed in https://github.com/ABAP-Logger/ABAP-Logger/issues/67#issuecomment-738303553 but time issues occured in the meantime.

`Thanks for all your work on this great logging framework`
All the credit should go to @epeterson320. Personnaly I joined the project as a maintainer a year ago.

2021-09-21 18:40 UTC, mbtools commented on src/zif_loggable_object.intf.abap
> +    METHODS get_message_table RETURNING VALUE(r_result) TYPE bapiret2_t.
FYI, I have greatly simplified the `add` method by dynamically determining if the input contains the required msg-fields for logging. I will create a PR once this one is merged.

2021-09-27 12:19 UTC, cavabap commented
I'll submit an updated PR for two different loggable objects, a simple one based on bapiret2_t and a complex one based on your tty_messages. Then for my customers I'll just implement the simple logger. I'm open to other naming suggestions...

2021-09-28 07:21 UTC, AlexandreHT commented
> I'll submit an updated PR for two different loggable objects, a simple one based on bapiret2_t and a complex one based on your tty_messages.

I'm sorry, I'll disagree on this. From an ABAP-Logger point of view, I don't see the value added of having 2 different interfaces (+ it opens the door of others interfaces for just bapiret1, etc.)

We could simplify the signature of ty_message and drop the dependancy on ``SYMSG`` (and avoid having a deep structure). Which would give us :
```ABAP
TYPES: begin of ty_message,
        MSGTY type SYMSGTY,
        MSGID type SYMSGID,
        MSGNO type SYMSGNO,
        MSGV1 type SYMSGV,
        MSGV2 type SYMSGV,
        MSGV3 type SYMSGV,
        MSGV4 type SYMSGV,
        exception type ref to cx_root, 
        string type string,
        context       type simple optional,
      end of ty_message,
      tty_message type standard table ty_message empty key.
```

I've re-read your initial requirement. I think the following would answer it (with the ty_message signature) : 

```ABAP
class zcx_my_abstract_exception_class definition
  public
  inheriting from CX_STATIC_CHECK
  create public.

  public section.
    interfaces zif_loggable_object.
endclass.

class zcx_my_abstract_exception_class implementation.
  method zif_loggable_object~get_message_table.
    loop at mt_bapiret2_t into data(bapiret2).
      append value #(
        MSGTY = bapiret2-TYPE
        MSGID = bapiret2-ID
        MSGNO = bapiret2-NUMBER
        MSGV1 = bapiret2-MESSAGE_V1
        MSGV2 = bapiret2-MESSAGE_V2
        MSGV3 = bapiret2-MESSAGE_V3
        MSGV4 = bapiret2-MESSAGE_V4 ) to rv_result.
    MSGV4.
  endmethod.
endclass.
```
```ABAP
 try.
  "...
  catch zcx_my_abstract_exception_class into data(exception).
    g_logger->add(exception).
endtry.
```

What do you think? Am I missing something?

2021-09-29 09:29 UTC, cavabap commented
I'm aware the the second interface "simple" isn't strictly required. I just dislike the complexity of the interface as it stands - but as you say - it will full-fill my purpose. I personally don't see the need to remove the deep structure to symsg. At least this way, its clear what fields belong to which use case.

But as you wrote, having a "simple" and a "complex" interface does open the door to more interfaces and I can see your point about why this isn't a good proposition.

So can you just accept the pull request as it stands?

On a side note, 
Is the code formatting (keywords are lowercase) intentional? Can I suggest formatting with @mbtools PR?
Also I see that in the case of add for the structure 'HRPAD_MESSAGE' there are no unit tests. Perhaps this ought to be tested?

2021-09-30 08:26 UTC, AlexandreHT commented
> I personally don't see the need to remove the deep structure to symsg. At least this way, its clear what fields belong to which use case.

That's what I thought when I wrote the proposition but for strings or exceptions, we'll need a type field to store the info. Which would give us 

```ABAP
TYPES: begin of ty_symsg,
               MSGID type SYMSGID,
               MSGNO type SYMSGNO,
               MSGV1 type SYMSGV,
               MSGV2 type SYMSGV,
               MSGV3 type SYMSGV,
               MSGV4 type SYMSGV,
            end of ty_symsg.

TYPES: begin of ty_message,
        type type SYMSGTY,
        symsg type ty_symsg,
        exception type ref to cx_root, 
        string type string,
      end of ty_message,
      tty_message type standard table ty_message empty key.
```

A SYmsg or bapiret2 message should therefore be mapped to 2 levels as such:

```ABAP
    loop at mt_bapiret2_t into data(bapiret2).
      append value #(
        type = bapiret2-TYPE
        symsg = value #(
                           MSGID = bapiret2-ID
                           MSGNO = bapiret2-NUMBER
                           MSGV1 = bapiret2-MESSAGE_V1
                           MSGV2 = bapiret2-MESSAGE_V2
                           MSGV3 = bapiret2-MESSAGE_V3
                           MSGV4 = bapiret2-MESSAGE_V4 )
                ) to rv_result.
    endloop.
```
I have not made my mind on what's better : a deep structure with ty_symsg (without type) or everything on the same level.

What do you think?

> Is the code formatting (keywords are lowercase) intentional? Can I suggest formatting with @mbtools PR?

Nope. It's a mix of copy/paste + code writing in the comment form on github :-) I'll wait a few more days before closing #96 but it looks like we're going that way. I'll update pretty print linter + code after your PR.

> Also I see that in the case of add for the structure 'HRPAD_MESSAGE' there are no unit tests. Perhaps this ought to be tested?

It would be a good idea indeed.

2021-10-04 10:02 UTC, cavabap commented
I prefer some kind of deep structure for symsg. If you want it to have the type removed then that is fine with me. I can see how when your working with strings and exceptions you'd not want to be using any fields from symsg.

So can I make that change and we'd finish the PR?

2021-10-04 10:21 UTC, AlexandreHT commented
Ok let's go that way. Thanks for your contribution!

Le lun. 4 oct. 2021 à 12:03, cavabap ***@***.***> a écrit :

> I prefer some kind of deep structure for symsg. If you want it to have the
> type removed then that is fine with me. I can see how when your working
> with strings and exceptions you'd not want to be using any fields from
> symsg.
>
> So can I make that change and we'd finish the PR?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ABAP-Logger/ABAP-Logger/pull/90#issuecomment-933331922>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKQ5V5EVWRILQ2C2JIEEF63UFF3VXANCNFSM5EEUR5BQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-04 14:43 UTC, cavabap commented
Okay. PR is updated.

2021-10-04 18:24 UTC, AlexandreHT approved these changes

2021-10-04 18:24 UTC, merged

2021-10-04 18:24 UTC, AlexandreHT commented
Thanks!